databaseChangeLog:
  - changeSet:
      id: 1
      author: NtsiK
      changes:
        - createTable:
            tableName: person
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(255)
                  constraints:
                    nullable: true
              - column:
                  name: surname
                  type: varchar(255)
                  constraints:
                    nullable: true
              - column:
                  name: idno
                  type: varchar(255)
                  constraints:
                    nullable: true


spring:
  main:
    web-application-type: none